[package]
name = "merkle"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive", "env"] }
rand = "0.8.5"
rs_merkle = "1.4.2"
sha2 = "0.10.8"
wasm = { path = "../wasm" }

