// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use methods::{GUEST_CODE_FOR_MERKEL_TREE_ELF, GUEST_CODE_FOR_MERKEL_TREE_ID};
use risc0_zkvm::{default_prover, ExecutorEnv};
use serde_json::Value;
use std::fs::File;
use std::io::BufReader;

fn main() {
    // Initialize tracing. In order to view logs, run `RUST_LOG=info cargo run`
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();

    let wasm =
        include_bytes!("../../../wasm/target/wasm32-unknown-unknown/release/wasm.wasm").to_vec();

    // Read the JSON file
    let file = File::open("../../../inputs/tsp.json").expect("Failed to open config file");
    let reader = BufReader::new(file);
    let json: Value = serde_json::from_reader(reader).expect("Failed to parse JSON");
    let graph: Vec<Vec<i32>> =
        serde_json::from_value(json["graph"].clone()).expect("Failed to parse graph from JSON");

    let env = ExecutorEnv::builder()
        .write(&wasm)
        .unwrap()
        .write(&graph)
        .unwrap()
        .build()
        .unwrap();

    // Obtain the default prover.
    let prover = default_prover();

    // Proof information by proving the specified ELF binary.
    // This struct contains the receipt along with statistics about execution of the guest
    let prove_info = prover.prove(env, GUEST_CODE_FOR_MERKEL_TREE_ELF).unwrap();

    let receipt = prove_info.receipt;
    let _output: u32 = receipt.journal.decode().unwrap();

    // The receipt was verified at the end of proving, but the below code is an
    // example of how someone else could verify this receipt.
    receipt.verify(GUEST_CODE_FOR_MERKEL_TREE_ID).unwrap();
}
