[workspace]
[package]
version = "0.1.0"
name = "bls-agg-rust-program"
edition = "2021"

[dependencies]
sp1-zkvm = "2.0.0"
wasmi = "0.36.1"
sp1-derive = "2.0.0"
wasm = { path = "../../wasm" }
serde_cbor = "0.11.2"
