[package]
name = "guest_code_for_prime_check"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.1.2", default-features = false, features = ['std'] }
wasm = { path = "../../../wasm" }
