[workspace]
[package]
version = "0.1.0"
name = "merkle-native-program"
edition = "2021"

[dependencies]
sp1-zkvm = "2.0.0"
eth_verify= { path = "../../native" }
sp1-derive = "2.0.0"
alloy-primitives = "0.8.5"

