[package]
name = "binary"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive", "env"] }
rand = "0.8.5"
serde_json = "1.0.128"

[lib]
name = "binary"
path = "src/lib.rs"
