[workspace]
[package]
version = "0.1.0"
name = "eth_verify-rust-script"
edition = "2021"

[dependencies]
sp1-sdk = "2.0.0"
clap = { version = "4.0", features = ["derive", "env"] }

[build-dependencies]
sp1-helper = "2.0.0"
