// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use methods::{GUEST_CODE_FOR_PRIME_CHECK_ELF, GUEST_CODE_FOR_PRIME_CHECK_ID};
use risc0_zkvm::{default_prover, ExecutorEnv};
use serde_json::Value;
use std::fs::File;
use std::io::BufReader;

fn main() {
    // Initialize tracing. In order to view logs, run `RUST_LOG=info cargo run`
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();

    let wasm = include_bytes!("../../../wasm/target/wasm32-unknown-unknown/release/wasm.wasm").to_vec();

    // Read the JSON file
    let file = File::open("../../../inputs/binary.json").expect("Failed to open input file");
    let reader = BufReader::new(file);
    let json: Value = serde_json::from_reader(reader).expect("Failed to parse JSON");

    // Extract the number from the JSON
    let input_json = json["list"].as_array().expect("Failed to parse list from JSON");
    let input_list: Vec<i32> = input_json.iter().map(|v| v.as_i64().expect("Failed to parse list from JSON") as i32).collect();
    let input_value = json["value"].as_i64().expect("Failed to parse value from JSON") as i32;
    println!("Input list: {}", input_list.len());
    println!("Input value: {}", input_value);

    let env = ExecutorEnv::builder()
        .write(&wasm).unwrap()
        .write(&input_list).unwrap()
        .write(&input_value).unwrap()
        .build()
        .unwrap();

    // Obtain the default prover.
    let prover = default_prover();

    // Proof information by proving the specified ELF binary.
    // This struct contains the receipt along with statistics about execution of the guest
    let prove_info = prover.prove(env, GUEST_CODE_FOR_PRIME_CHECK_ELF).unwrap();

    let receipt = prove_info.receipt;
    let _output: u32 = receipt.journal.decode().unwrap();

    // The receipt was verified at the end of proving, but the below code is an
    // example of how someone else could verify this receipt.
    receipt.verify(GUEST_CODE_FOR_PRIME_CHECK_ID).unwrap();
}
