// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use methods::{GUEST_CODE_FOR_BINARY_SEARCH_ELF, GUEST_CODE_FOR_BINARY_SEARCH_ID};
use risc0_zkvm::{default_prover, ExecutorEnv};
use serde_json::Value;
use std::fs::File;
use std::io::BufReader;

fn main() {
    // Initialize tracing. In order to view logs, run `RUST_LOG=info cargo run`
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();

    let file = File::open("../../../inputs/binary.json").expect("Failed to open input file");
    let reader = BufReader::new(file);
    let json: Value = serde_json::from_reader(reader).expect("Failed to parse JSON");

    // Extract the number from the JSON
    let input_json = json["list"]
        .as_array()
        .expect("Failed to parse list from JSON");
    let input_list: Vec<i32> = input_json
        .iter()
        .map(|v| v.as_i64().expect("Failed to parse list from JSON") as i32)
        .collect();
    let input_value = json["value"]
        .as_i64()
        .expect("Failed to parse value from JSON") as i32;

    let env = ExecutorEnv::builder()
        .write(&input_value)
        .unwrap()
        .write(&input_list)
        .unwrap()
        .build()
        .unwrap();

    // Obtain the default prover.
    let prover = default_prover();

    let prove_info = prover.prove(env, GUEST_CODE_FOR_BINARY_SEARCH_ELF).unwrap();

    let receipt = prove_info.receipt;
    let _output: u32 = receipt.journal.decode().unwrap();
    receipt.verify(GUEST_CODE_FOR_BINARY_SEARCH_ID).unwrap();
}
