[package]
name = "poseidon-wasm_risc_zero-methods-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.1.2", default-features = false, features = ['std'] }
wasm = { path = "../../../wasm" }
wasmi = "0.31"
bincode = "1.3.3"